package com.staticflow;

import javax.swing.*;
import java.awt.*;

/**
 * Custom UI for the `BOR` extension
 */
public class BorExtensionUI extends JPanel {
    private JPanel mainPanel;
    private JList<String> breakpointList;
    private JScrollPane breakpointScrollPane;
    private JButton deleteSelectedBreakpointsButton;


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.setMinimumSize(new Dimension(800, 500));
        mainPanel.setPreferredSize(new Dimension(800, 500));
        deleteSelectedBreakpointsButton.setText("Delete Selected Breakpoints");
        mainPanel.add(deleteSelectedBreakpointsButton, BorderLayout.NORTH);
        breakpointScrollPane = new JScrollPane();
        mainPanel.add(breakpointScrollPane, BorderLayout.CENTER);
        breakpointScrollPane.setViewportView(breakpointList);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    public JList<String> getBreakpointList() {
        return breakpointList;
    }

    private void createUIComponents() {
        mainPanel = new JPanel();
        deleteSelectedBreakpointsButton = new JButton();
        deleteSelectedBreakpointsButton.addActionListener(e -> {
            int index = breakpointList.getSelectedIndices().length - 1;

            while (breakpointList.getSelectedIndices().length != 0) {
                ExtensionState.getInstance().getBreakpoints().removeElementAt(breakpointList.getSelectedIndices()[index--]);
            }
        });
        breakpointList = new JList<>();
        add(mainPanel);
    }
}
